const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.scripts([
    'resources/frontend/js/jquery.min.js',
    'resources/frontend/js/bootstrap.min.js',
    'resources/frontend/js/nifty.min.js',
    'resources/frontend/js/demo/nifty-demo.min.js',
    'resources/frontend/plugins/flot-charts/jquery.flot.min.js',
    'resources/frontend/plugins/flot-charts/jquery.flot.resize.min.js',
    'resources/frontend/plugins/flot-charts/jquery.flot.tooltip.min.js',
    'resources/frontend/plugins/sparkline/jquery.sparkline.min.js',
    'resources/frontend/js/demo/dashboard.js',
    'resources/frontend/plugins/pace/pace.min.js',
    // 'resources/frontend/js/demo/bg-images.js',
    // 'resources/frontend/js/demo/dashboard-2.js',
    // 'resources/frontend/js/demo/dashboard.js',
    // 'resources/frontend/js/demo/easy-pie-chart.js',
    // 'resources/frontend/js/demo/flot-charts.js',
    // 'resources/frontend/js/demo/form-component.js',
    // 'resources/frontend/js/demo/form-file-upload.js',
    // 'resources/frontend/js/demo/form-text-editor.js',
    // 'resources/frontend/js/demo/form-validation.js',
    // 'resources/frontend/js/demo/form-wizard.js',
    // 'resources/frontend/js/demo/icons.js',
    // 'resources/frontend/js/demo/mail.js',
    // 'resources/frontend/js/demo/misc-fullcalendar.js',
    // 'resources/frontend/js/demo/misc-gmaps.js',
    // 'resources/frontend/js/demo/morris-js.js',
    // 'resources/frontend/js/demo/nifty-demo.min.js',
    // 'resources/frontend/js/demo/sparklines.js',
    // 'resources/frontend/js/demo/tables-bs-table.js',
    // 'resources/frontend/js/demo/tables-datatables.js',
    // 'resources/frontend/js/demo/tables-footable.js',
    // 'resources/frontend/js/demo/ui-alerts.js',
    // 'resources/frontend/js/demo/ui-buttons.js',
    // 'resources/frontend/js/demo/ui-modals.js',
    // 'resources/frontend/js/demo/ui-panels.js',
    // 'resources/frontend/js/demo/widgets.js',
    // 'resources/frontend/js/demo/x-editable-data.js',
    // 'resources/frontend/js/bootstrap.min.js',
    // 'resources/frontend/js/jquery.min.js',
    // 'resources/frontend/js/nifty.min.js',
    // 'resources/frontend/plugins/bootbox/bootbox.min.js',
    // 'resources/frontend/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js',
    // 'resources/frontend/plugins/bootstrap-markdown/js/bootstrap-markdown.js',
    // 'resources/frontend/plugins/bootstrap-markdown/js/markdown.js',
    // 'resources/frontend/plugins/bootstrap-markdown/js/to-markdown.js',
    // 'resources/frontend/plugins/bootstrap-select/bootstrap-select.min.js',
    // 'resources/frontend/plugins/bootstrap-table/bootstrap-table.min.js',
    // 'resources/frontend/plugins/bootstrap-table/extensions/editable/bootstrap-table-editable.js',
    // 'resources/frontend/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.js',
    // 'resources/frontend/plugins/bootstrap-timepicker/bootstrap-timepicker.min.js',
    // 'resources/frontend/plugins/bootstrap-validator/bootstrapValidator.min.js',
    // 'resources/frontend/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js',
    // 'resources/frontend/plugins/chosen/chosen.jquery.min.js',
    // 'resources/frontend/plugins/clipboard-js/clipboard.min.js',
    // 'resources/frontend/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js',
    // 'resources/frontend/plugins/dropzone/dropzone.min.js',
    // 'resources/frontend/plugins/easy-pie-chart/jquery.easypiechart.min.js',
    // 'resources/frontend/plugins/flot-charts/jquery.flot.categories.min.js',
    // 'resources/frontend/plugins/flot-charts/jquery.flot.min.js',
    // 'resources/frontend/plugins/flot-charts/jquery.flot.orderBars.min.js',
    // 'resources/frontend/plugins/flot-charts/jquery.flot.pie.min.js',
    // 'resources/frontend/plugins/flot-charts/jquery.flot.resize.min.js',
    // 'resources/frontend/plugins/flot-charts/jquery.flot.tooltip.min.js',
    // 'resources/frontend/plugins/fooTable/dist/footable.all.min.js',
    // 'resources/frontend/plugins/fullcalendar/fullcalendar.min.js',
    // 'resources/frontend/plugins/fullcalendar/lib/jquery-ui.custom.min.js',
    // 'resources/frontend/plugins/fullcalendar/lib/moment.min.js',
    // 'resources/frontend/plugins/gauge-js/gauge.min.js',
    // 'resources/frontend/plugins/gmaps/gmaps.js',
    // 'resources/frontend/plugins/jquery-match-height/jquery-match-height.min.js',
    // 'resources/frontend/plugins/jquery-ui/jquery-ui.min.js',
    // 'resources/frontend/plugins/jstree/jstree.min.js',
    // 'resources/frontend/plugins/masked-input/jquery.maskedinput.min.js',
    // 'resources/frontend/plugins/masonry/masonry.pkgd.min.js',
    // 'resources/frontend/plugins/momentjs/moment.min.js',
    // 'resources/frontend/plugins/morris-js/raphael-js/raphael.min.js',
    // 'resources/frontend/plugins/morris-js/morris.min.js',
    // 'resources/frontend/plugins/nestable-list/jquery.nestable.js',
    // 'resources/frontend/plugins/noUiSlider/nouislider.min.js',
    // 'resources/frontend/plugins/pace/pace.min.js',
    // 'resources/frontend/plugins/select2/js/select2.min.js',
    // 'resources/frontend/plugins/skycons/skycons.min.js',
    // 'resources/frontend/plugins/sparkline/jquery.sparkline.min.js',
    // 'resources/frontend/plugins/summernote/summernote.min.js',
    // 'resources/frontend/plugins/switchery/switchery.min.js',
    // 'resources/frontend/plugins/unitegallery/js/unitegallery.min.js',
    // 'resources/frontend/plugins/unitegallery/themes/carousel/ug-theme-carousel.js',
    // 'resources/frontend/plugins/unitegallery/themes/compact/ug-theme-compact.js',
    // 'resources/frontend/plugins/unitegallery/themes/default/ug-theme-default.js',
    // 'resources/frontend/plugins/unitegallery/themes/grid/ug-theme-grid.js',
    // 'resources/frontend/plugins/unitegallery/themes/slider/ug-theme-slider.js',
    // 'resources/frontend/plugins/unitegallery/themes/tiles/ug-theme-tiles.js',
    // 'resources/frontend/plugins/unitegallery/themes/tilesgrid/ug-theme-tilesgrid.js',
    // 'resources/frontend/plugins/x-editable/inputs-ext/address/address.js',
    // 'resources/frontend/plugins/x-editable/inputs-ext/mockjax/jquery.mockjax.js',
    // 'resources/frontend/plugins/x-editable/inputs-ext/typeaheadjs/typeaheadjs.js',
    // 'resources/frontend/plugins/x-editable/inputs-ext/typeaheadjs/lib/typeahead.js',
    // 'resources/frontend/plugins/x-editable/js/bootstrap-editable.min.js',
], 'public/js/main.js')
    .styles([
    'resources/frontend/css/bootstrap.min.css',
    'resources/frontend/css/nifty.min.css',
    'resources/frontend/css/demo/nifty-demo-icons.min.css',
    'resources/frontend/plugins/pace/pace.min.css',
    'resources/frontend/css/demo/nifty-demo.min.css',
    // 'resources/frontend/css/bootstrap.min.css',
    // 'resources/frontend/css/nifty.min.css',
    // 'resources/frontend/css/demo/nifty-demo-icons.min.css',
    // 'resources/frontend/css/demo/nifty-demo.min.css',
    // 'resources/frontend/css/themes/type-c/theme-navy.min.css',
    // 'resources/frontend/css/themes/type-d/theme-navy.min.css',
    // 'resources/frontend/plugins/animate-css/animate.min.css',
    // 'resources/frontend/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css',
    // 'resources/frontend/plugins/bootstrap-markdown/css/bootstrap-markdown.min.css',
    // 'resources/frontend/plugins/bootstrap-select/bootstrap-select.min.css',
    // 'resources/frontend/plugins/bootstrap-table/bootstrap-table.min.css',
    // 'resources/frontend/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.css',
    // 'resources/frontend/plugins/bootstrap-timepicker/bootstrap-timepicker.min.css',
    // 'resources/frontend/plugins/bootstrap-validator/bootstrapValidator.min.css',
    // 'resources/frontend/plugins/chosen/chosen.min.css',
    // 'resources/frontend/plugins/css-loaders/css/css-loaders.css',
    // 'resources/frontend/plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css',
    // 'resources/frontend/plugins/dropzone/dropzone.min.css',
    // 'resources/frontend/plugins/flag-icon-css/css/flag-icon.min.css',
    // 'resources/frontend/plugins/font-awesome/css/font-awesome.min.css',
    // 'resources/frontend/plugins/fooTable/css/footable.core.css',
    // 'resources/frontend/plugins/fullcalendar/fullcalendar.min.css',
    // 'resources/frontend/plugins/fullcalendar/nifty-skin/fullcalendar-nifty.min.css',
    // 'resources/frontend/plugins/ionicons/css/ionicons.min.css',
    // 'resources/frontend/plugins/jquery-ui/jquery-ui.min.css',
    // 'resources/frontend/plugins/jstree/themes/default/style.min.css',
    // 'resources/frontend/plugins/morris-js/morris.min.css',
    // 'resources/frontend/plugins/nestable-list/nestable-list.min.css',
    // 'resources/frontend/plugins/noUiSlider/nouislider.min.css',
    // 'resources/frontend/plugins/pace/pace.min.css',
    // 'resources/frontend/plugins/select2/css/select2.min.css',
    // 'resources/frontend/plugins/spinkit/css/spinkit.min.css',
    // 'resources/frontend/plugins/summernote/summernote.min.css',
    // 'resources/frontend/plugins/switchery/switchery.min.css',
    // 'resources/frontend/plugins/themify-icons/themify-icons.min.css',
    // 'resources/frontend/plugins/transactional-email-templates/templates/styles.css',
    // 'resources/frontend/plugins/unitegallery/css/unitegallery.min.css',
    // 'resources/frontend/plugins/unitegallery/themes/default/ug-theme-default.css',
    // 'resources/frontend/plugins/weather-icons/css/weather-icons-wind.min.css',
    // 'resources/frontend/plugins/weather-icons/css/weather-icons.min.css',
    // 'resources/frontend/plugins/x-editable/css/bootstrap-editable.css',
    // 'resources/frontend/plugins/x-editable/inputs-ext/address/address.css',
    // 'resources/frontend/plugins/x-editable/inputs-ext/typeaheadjs/lib/typeahead.js-bootstrap.css',
], 'public/css/main.css')
    .js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
    ]);

// mix.js('resources/js/app.js', 'public/js')
//     .postCss('resources/css/app.css', 'public/css', [
//         require('postcss-import'),
//         require('tailwindcss'),
//     ]);

if (mix.inProduction()) {
    mix.version();
}
